title: ":: Steeplejack"
email: your-email@domain.com
description: >
  NodeJS. With less mess. Get rid of the boilerplate and build
  highly testable NodeJS applications fast.
default_img: https://getsteeplejack.com/some/img.png
baseurl: ""
url: ""
github_fork_url: https://github.com/steeplejack-js/steeplejack
github_url: https://github.com/steeplejack-js/steeplejack-js.github.io
twitter: riggerthegeek

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

author: Simon Emms
author_link: http://simonemms.com

permalink: pretty

empty_array: []

colors:
  api: warning
  concepts: success
  getting-started: danger
